/**
 * Design Skill Prompt — injected into arena battles when design skill is active.
 * Based on the frontend-design skill but hardened for local model reliability.
 *
 * Key differences from the raw skill:
 * - Bans base64/data-uri SVGs (models generate broken SVGs that render as black boxes)
 * - Forces z-index: -1 on decorative overlays (models set z-index: 100+ which covers content)
 * - Forces inline CSS (models create separate files that don't load from file://)
 * - Provides CSS-only noise texture example (safe alternative to SVG)
 */
export const DESIGN_SKILL_ADDENDUM = `
CRITICAL DESIGN REQUIREMENTS — follow these EXACTLY:

TYPOGRAPHY: Do NOT use generic fonts (Arial, Inter, Roboto, system fonts). Import 2 Google Fonts via @import in the <style> tag — one distinctive display font (Syne, Clash Display, Cabinet Grotesk, Satoshi, Playfair Display, or Space Grotesk) and one refined body font (DM Sans, Source Sans, or Outfit).

COLOR: Commit to a BOLD color palette. No timid, evenly-distributed colors. Use a dominant dark background (#0a0a1a or #1a0533) with ONE sharp accent color that pops (electric violet #8b5cf6, cyan #06b6d4, or amber #f59e0b). Use CSS custom properties for consistency.

MOTION: Add CSS animations — staggered page-load reveal using animation-delay (0.1s increments), hover effects that surprise (transform: scale(1.02) translateY(-4px) + box-shadow glow), and a subtle gradient shift on the hero. Keep animations under 1s duration.

SPATIAL COMPOSITION: Break the predictable grid. Generous negative space in the hero (min-height: 80vh, centered content). Feature cards with depth: backdrop-filter: blur(10px), semi-transparent backgrounds (rgba), subtle borders (rgba(255,255,255,0.08)).

BACKGROUNDS AND TEXTURES:
- For noise/grain: use ONLY CSS. Example: background-image: repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(255,255,255,0.03) 2px, rgba(255,255,255,0.03) 4px);
- Do NOT use base64 SVGs, data URIs, or inline SVG for textures — they render incorrectly in many environments.
- All decorative pseudo-elements (::before, ::after) MUST use z-index: -1 so they stay BEHIND content.
- Use radial-gradient or linear-gradient for atmosphere, not solid colors.

DETAILS: Custom ::selection color matching accent. Smooth scroll (scroll-behavior: smooth on html). Subtle border-radius (12-20px on cards). All CSS must be inline in a <style> tag — no separate CSS files.

The result should look like it was designed by a senior UI designer, NOT generated by AI. Distinctive, memorable, striking.`;
