/**
 * Arena Design Skill Battle
 *
 * Devstral (plain) vs Devstral (with frontend-design skill)
 * Same model, same challenge — only difference is design instructions.
 *
 * Run: npx playwright test e2e/arena-design-skill-battle.test.ts
 */
import { test, type ElectronApplication, type Page } from '@playwright/test';
import { _electron as electron } from 'playwright';
import * as path from 'path';
import * as fs from 'fs';
import { execSync } from 'child_process';

const PROJECT_ROOT = path.resolve(__dirname, '..');
const SS_DIR = path.join(__dirname, 'screenshots', 'arena-design');
fs.mkdirSync(SS_DIR, { recursive: true });

test.setTimeout(600_000);

let app: ElectronApplication;
let page: Page;

async function shot(name: string) {
  await page.screenshot({ path: path.join(SS_DIR, `${name}.png`), fullPage: false });
  console.log(`  📸 ${name}.png`);
}

const DESIGN_SKILL_PROMPT = `Build a modern landing page for an AI productivity tool called "FlowState". Include a hero section with headline and CTA button, a 3-column feature grid, a testimonials section with 2 quotes, and a footer. Use a dark theme with purple and blue gradient accents. Use write_file to create index.html with ALL CSS inline in a <style> tag.

CRITICAL DESIGN REQUIREMENTS — follow these EXACTLY:

TYPOGRAPHY: Do NOT use generic fonts like Arial, Inter, Roboto, or system fonts. Instead, import 2 Google Fonts — one distinctive display font (like Syne, Clash Display, Cabinet Grotesk, or Satoshi) and one refined body font. Use @import in the <style> tag.

COLOR: Commit to a BOLD color palette. No timid, evenly-distributed colors. Use a dominant dark background with ONE sharp accent color that pops. Consider deep indigo (#1a0533) with electric violet (#8b5cf6) accents, or midnight blue with cyan sparks.

MOTION: Add CSS animations — a staggered page-load reveal (elements fade in with animation-delay), hover effects that surprise (scale + glow + shadow shifts), and a subtle gradient animation on the hero background.

SPATIAL COMPOSITION: Break the grid. Use asymmetric layouts, overlapping elements, generous negative space. The hero should feel expansive. Feature cards should have depth (layered shadows, glassmorphism, or subtle borders).

BACKGROUNDS: Create atmosphere with gradient meshes, noise/grain overlays (use CSS or inline SVG), or layered transparencies. No flat solid colors.

DETAILS: Add a subtle noise texture overlay on the body. Use backdrop-filter: blur() for glass effects. Custom selection colors. Smooth scroll behavior. Decorative geometric shapes (circles, lines) as accents.

The result should look like it was designed by a senior UI designer, NOT generated by AI. It should be MEMORABLE and STRIKING — the kind of page someone screenshots and shares.`;

test.beforeAll(async () => {
  console.log('Building LiteBench...');
  execSync('npx electron-vite build', { cwd: PROJECT_ROOT, stdio: 'pipe' });

  const devDb = path.join(PROJECT_ROOT, 'backend', 'litebench.db');
  const builtDb = path.join(PROJECT_ROOT, 'out', 'main', 'backend', 'litebench.db');
  fs.mkdirSync(path.dirname(builtDb), { recursive: true });
  if (fs.existsSync(devDb)) fs.copyFileSync(devDb, builtDb);

  app = await electron.launch({
    args: [path.join(PROJECT_ROOT, 'out', 'main', 'index.js')],
    cwd: PROJECT_ROOT,
    env: { ...process.env, NODE_ENV: 'development' },
  });

  page = await app.firstWindow();
  await page.waitForLoadState('domcontentloaded');

  page.on('console', (msg) => {
    if (msg.type() === 'error') console.log(`  [ERR] ${msg.text()}`);
  });

  await page.waitForTimeout(3000);
  console.log('Ready.\n');
});

test.afterAll(async () => {
  console.log('\n=== APP LEFT OPEN — REVIEW THE GENERATED SITES ===\n');
});

test('Devstral with frontend-design skill — FlowState landing page', async () => {
  // Open Arena
  await page.locator('button[title="Battle Arena"]').click();
  await page.waitForTimeout(1000);

  // Select LM Studio endpoint
  await page.waitForTimeout(3000);
  const endpointSelect = page.locator('select').first();
  const allOptions = await endpointSelect.locator('option').all();

  for (const opt of allOptions) {
    const val = await opt.getAttribute('value');
    const text = await opt.textContent();
    if (val && text) {
      await endpointSelect.selectOption(val);
      await page.waitForTimeout(3000);
      const msel = page.locator('select').nth(1);
      const firstModel = await msel.locator('option').first().textContent();
      if (firstModel && firstModel !== 'No models' && firstModel !== 'Select model') {
        console.log(`Using endpoint: ${text}`);
        break;
      }
    }
  }

  // Find Devstral in the model list
  const modelSelect = page.locator('select').nth(1);
  const modelOptions = await modelSelect.locator('option').allTextContents();
  const devstral = modelOptions.find(m => m.toLowerCase().includes('devstral'));

  if (!devstral) {
    console.log('⚠️ Devstral not found. Available: ' + modelOptions.join(', '));
    console.log('Using first available model instead.');
  }

  const targetModel = devstral || modelOptions.find(m => m !== 'Select model' && m !== 'No models') || '';
  console.log(`Model: ${targetModel}`);

  // Add model TWICE (Devstral vs Devstral)
  await modelSelect.selectOption({ label: targetModel });
  await page.waitForTimeout(200);
  await page.locator('button[title="Add model"]').click();
  await page.waitForTimeout(300);

  await modelSelect.selectOption({ label: targetModel });
  await page.waitForTimeout(200);
  await page.locator('button[title="Add model"]').click();
  await page.waitForTimeout(300);

  console.log('Added 2x ' + targetModel);
  await shot('01-models-selected');

  // Set the design-skill-enhanced prompt
  const textarea = page.locator('textarea').first();
  await textarea.fill('');
  await textarea.fill(DESIGN_SKILL_PROMPT);
  console.log('Design skill prompt set (' + DESIGN_SKILL_PROMPT.length + ' chars)');
  await shot('02-prompt-set');

  // Start battle — click and verify phase transition
  const battleBtn = page.locator('button').filter({ hasText: /Battle/i }).first();
  await battleBtn.click();
  console.log('⚡ Battle button clicked');
  await page.waitForTimeout(5000);

  // Check if phase transitioned or we're still on config
  const phaseCheck = await page.evaluate(() => {
    try {
      // Try to read errors from the page
      const bodyText = document.body.innerText;
      const hasBuilding = /Building|in Progress/i.test(bodyText);
      const hasError = /error/i.test(bodyText);
      return { hasBuilding, hasError, snippet: bodyText.substring(0, 500) };
    } catch { return { hasBuilding: false, hasError: false, snippet: '' }; }
  });
  console.log(`  Phase transitioned to building: ${phaseCheck.hasBuilding}`);
  if (!phaseCheck.hasBuilding) {
    console.log('  ⚠️ Still on config — battle may have failed');
    console.log('  Page text snippet:', phaseCheck.snippet.substring(0, 200));
  }
  await shot('03-battle-started');

  // Monitor
  const maxWait = 8 * 60_000;
  const startTime = Date.now();
  let done = false;
  let n = 0;

  while (!done && Date.now() - startTime < maxWait) {
    await page.waitForTimeout(20_000);
    n++;
    const elapsed = Math.round((Date.now() - startTime) / 1000);

    const resultsText = await page.locator('text=/Results|Judging|Pick Winner/i').count();
    if (resultsText > 0) {
      done = true;
      console.log(`✅ Done in ${elapsed}s`);
    } else {
      console.log(`  ... ${elapsed}s`);
    }

    if (n % 3 === 0 || done) await shot(`04-progress-${n}`);
  }

  if (!done) {
    console.log('⚠️ Timed out');
    await shot('04-timeout');
  }

  await page.waitForTimeout(3000);
  await shot('05-results');

  // Find and report generated files
  const battlesDir = path.join(PROJECT_ROOT, 'out', 'main', 'battles');
  if (fs.existsSync(battlesDir)) {
    const dirs = fs.readdirSync(battlesDir).sort();
    const latest = dirs[dirs.length - 1];
    if (latest) {
      const battlePath = path.join(battlesDir, latest);
      const comps = fs.readdirSync(battlePath).filter(f =>
        fs.statSync(path.join(battlePath, f)).isDirectory()
      );

      for (const comp of comps) {
        const compPath = path.join(battlePath, comp);
        const files = fs.readdirSync(compPath);
        const indexPath = path.join(compPath, 'index.html');
        if (fs.existsSync(indexPath)) {
          const size = fs.statSync(indexPath).size;
          console.log(`\n${comp}: index.html (${size} bytes)`);

          // Open in browser
          execSync(`start "" "${indexPath}"`);
          console.log(`  Opened in browser`);
        }
      }

      console.log(`\nBattle ID: ${latest}`);
      console.log(`Path: ${battlePath}`);
    }
  }
});
