/**
 * Arena Battle: Devstral vs Devstral Abliterated
 *
 * Same 24B model, one stock, one uncensored. Design skill prompt.
 * Sequential execution. Results left for manual judging.
 *
 * Run: npx playwright test e2e/arena-devstral-abliterated.test.ts
 */
import { test, type ElectronApplication, type Page } from '@playwright/test';
import { _electron as electron } from 'playwright';
import * as path from 'path';
import * as fs from 'fs';
import { execSync } from 'child_process';

const PROJECT_ROOT = path.resolve(__dirname, '..');
const SS_DIR = path.join(__dirname, 'screenshots', 'arena-abliterated');
fs.mkdirSync(SS_DIR, { recursive: true });

test.setTimeout(600_000);

let app: ElectronApplication;
let page: Page;

async function shot(name: string) {
  await page.screenshot({ path: path.join(SS_DIR, `${name}.png`), fullPage: false });
  console.log(`  📸 ${name}.png`);
}

const DESIGN_SKILL_PROMPT = `Build a modern landing page for an AI productivity tool called "FlowState". Include a hero section with headline and CTA button, a 3-column feature grid, a testimonials section with 2 quotes, and a footer. Use a dark theme with purple and blue gradient accents. Use write_file to create index.html with ALL CSS inline in a <style> tag.

CRITICAL DESIGN REQUIREMENTS — follow these EXACTLY:

TYPOGRAPHY: Do NOT use generic fonts like Arial, Inter, Roboto, or system fonts. Instead, import 2 Google Fonts — one distinctive display font (like Syne, Clash Display, Cabinet Grotesk, or Satoshi) and one refined body font. Use @import in the <style> tag.

COLOR: Commit to a BOLD color palette. No timid, evenly-distributed colors. Use a dominant dark background with ONE sharp accent color that pops. Consider deep indigo (#1a0533) with electric violet (#8b5cf6) accents, or midnight blue with cyan sparks.

MOTION: Add CSS animations — a staggered page-load reveal (elements fade in with animation-delay), hover effects that surprise (scale + glow + shadow shifts), and a subtle gradient animation on the hero background.

SPATIAL COMPOSITION: Break the grid. Use asymmetric layouts, overlapping elements, generous negative space. The hero should feel expansive. Feature cards should have depth (layered shadows, glassmorphism, or subtle borders).

BACKGROUNDS: Create atmosphere with gradient meshes, noise/grain overlays (use CSS or inline SVG), or layered transparencies. No flat solid colors.

DETAILS: Add a subtle noise texture overlay on the body. Use backdrop-filter: blur() for glass effects. Custom selection colors. Smooth scroll behavior. Decorative geometric shapes (circles, lines) as accents.

The result should look like it was designed by a senior UI designer, NOT generated by AI. It should be MEMORABLE and STRIKING.`;

const MODEL_STOCK = 'mistralai/devstral-small-2-2512';
const MODEL_ABLITERATED = 'huihui-devstral-small-2-24b-instruct-2512-abliterated-i1';

test.beforeAll(async () => {
  console.log('Building LiteBench...');
  execSync('npx electron-vite build', { cwd: PROJECT_ROOT, stdio: 'pipe' });

  const devDb = path.join(PROJECT_ROOT, 'backend', 'litebench.db');
  const builtDb = path.join(PROJECT_ROOT, 'out', 'main', 'backend', 'litebench.db');
  fs.mkdirSync(path.dirname(builtDb), { recursive: true });
  if (fs.existsSync(devDb)) fs.copyFileSync(devDb, builtDb);

  app = await electron.launch({
    args: [path.join(PROJECT_ROOT, 'out', 'main', 'index.js')],
    cwd: PROJECT_ROOT,
    env: { ...process.env, NODE_ENV: 'development' },
  });

  page = await app.firstWindow();
  await page.waitForLoadState('domcontentloaded');

  page.on('console', (msg) => {
    if (msg.type() === 'error') console.log(`  [ERR] ${msg.text()}`);
  });
  page.on('pageerror', (err) => console.log(`  [PAGE ERR] ${err.message}`));

  await page.waitForTimeout(3000);
  console.log('Ready.\n');
});

test.afterAll(async () => {
  console.log('\n=== APP LEFT OPEN — REVIEW THE GENERATED SITES ===\n');
});

test('Devstral Stock vs Devstral Abliterated — Design Skill Battle', async () => {
  // Open Arena
  console.log('── Opening Arena ──');
  await page.locator('button[title="Battle Arena"]').click();
  await page.waitForTimeout(1000);

  // Wait for endpoints to load + select LM Studio
  await page.waitForTimeout(3000);
  const endpointSelect = page.locator('select').first();
  const allOptions = await endpointSelect.locator('option').all();

  for (const opt of allOptions) {
    const val = await opt.getAttribute('value');
    const text = await opt.textContent();
    if (val && text && text.includes('LM Studio')) {
      await endpointSelect.selectOption(val);
      console.log(`  Endpoint: ${text}`);
      break;
    } else if (val && text) {
      // Try any endpoint that has models
      await endpointSelect.selectOption(val);
      await page.waitForTimeout(2000);
      const msel = page.locator('select').nth(1);
      const mcount = await msel.locator('option').count();
      if (mcount > 2) {
        console.log(`  Endpoint: ${text} (${mcount} models)`);
        break;
      }
    }
  }

  await page.waitForTimeout(3000);
  const modelSelect = page.locator('select').nth(1);
  const addBtn = page.locator('button[title="Add model"]');

  // Add stock Devstral
  console.log('\n── Adding Models ──');
  try {
    await modelSelect.selectOption({ label: MODEL_STOCK });
    await page.waitForTimeout(200);
    await addBtn.click();
    console.log(`  ✅ Added: ${MODEL_STOCK}`);
  } catch {
    console.log(`  ⚠️ Could not find ${MODEL_STOCK}, trying partial match`);
    const options = await modelSelect.locator('option').allTextContents();
    const match = options.find(o => o.toLowerCase().includes('devstral') && !o.includes('abliterated'));
    if (match) {
      await modelSelect.selectOption({ label: match });
      await page.waitForTimeout(200);
      await addBtn.click();
      console.log(`  ✅ Added: ${match}`);
    }
  }
  await page.waitForTimeout(300);

  // Add abliterated Devstral
  try {
    await modelSelect.selectOption({ label: MODEL_ABLITERATED });
    await page.waitForTimeout(200);
    await addBtn.click();
    console.log(`  ✅ Added: ${MODEL_ABLITERATED}`);
  } catch {
    console.log(`  ⚠️ Could not find ${MODEL_ABLITERATED}, trying partial match`);
    const options = await modelSelect.locator('option').allTextContents();
    const match = options.find(o => o.toLowerCase().includes('abliterated'));
    if (match) {
      await modelSelect.selectOption({ label: match });
      await page.waitForTimeout(200);
      await addBtn.click();
      console.log(`  ✅ Added: ${match}`);
    }
  }
  await page.waitForTimeout(300);

  await shot('01-models-selected');

  // Set design skill prompt
  console.log('\n── Setting Prompt ──');
  const textarea = page.locator('textarea').first();
  await textarea.fill('');
  await textarea.fill(DESIGN_SKILL_PROMPT);
  console.log(`  Prompt set (${DESIGN_SKILL_PROMPT.length} chars)`);
  await shot('02-prompt-set');

  // Start battle
  console.log('\n── STARTING BATTLE ──');
  const battleBtn = page.locator('button').filter({ hasText: /Battle/i }).first();
  const isEnabled = await battleBtn.isEnabled();
  console.log(`  Battle button enabled: ${isEnabled}`);

  if (!isEnabled) {
    console.log('  ⚠️ Button not enabled — dumping page state');
    await shot('03-not-enabled');
    return;
  }

  await battleBtn.click();
  console.log('  ⚡ Battle started! (sequential — stock Devstral first, then abliterated)');
  await page.waitForTimeout(5000);
  await shot('03-battle-started');

  // Monitor progress
  console.log('\n── Monitoring ──');
  const maxWait = 10 * 60_000; // 10 min — two 24B models need time
  const startTime = Date.now();
  let done = false;
  let n = 0;

  while (!done && Date.now() - startTime < maxWait) {
    await page.waitForTimeout(20_000);
    n++;
    const elapsed = Math.round((Date.now() - startTime) / 1000);

    const resultsText = await page.locator('text=/Judging|Pick Winner/i').count();
    if (resultsText > 0) {
      done = true;
      console.log(`  ✅ Battle complete! (${elapsed}s)`);
    } else {
      // Check for phase indicators
      const buildingText = await page.locator('text=/Building|in Progress|Starting battle/i').count();
      const competitorText = await page.locator('text=/competitor|terminal|preview/i').count();
      console.log(`  ... ${elapsed}s — building: ${buildingText > 0}, competitor panes: ${competitorText > 0}`);
    }

    if (n % 3 === 0 || done) await shot(`04-progress-${n}`);
  }

  if (!done) {
    console.log('  ⚠️ Timed out after 10 minutes');
    await shot('04-timeout');
  }

  await page.waitForTimeout(3000);
  await shot('05-results');

  // Report generated files
  console.log('\n── Generated Files ──');
  const battlesDir = path.join(PROJECT_ROOT, 'out', 'main', 'battles');
  if (fs.existsSync(battlesDir)) {
    const dirs = fs.readdirSync(battlesDir).sort();
    const latest = dirs[dirs.length - 1];
    if (latest) {
      const battlePath = path.join(battlesDir, latest);
      const comps = fs.readdirSync(battlePath).filter(f =>
        fs.statSync(path.join(battlePath, f)).isDirectory()
      );

      for (const comp of comps) {
        const compPath = path.join(battlePath, comp);
        const files = fs.readdirSync(compPath);
        const indexPath = path.join(compPath, 'index.html');
        if (fs.existsSync(indexPath)) {
          const size = fs.statSync(indexPath).size;
          const model = comp === 'competitor-0' ? 'Stock Devstral' : 'Abliterated Devstral';
          console.log(`  ${model} (${comp}): index.html — ${size} bytes`);
          execSync(`start "" "${indexPath}"`);
          console.log(`    Opened in browser`);
        } else {
          const model = comp === 'competitor-0' ? 'Stock Devstral' : 'Abliterated Devstral';
          console.log(`  ${model} (${comp}): ${files.length > 0 ? files.join(', ') : 'EMPTY (DNF)'}`);
        }
      }

      console.log(`\n  Battle ID: ${latest}`);
      console.log(`  Path: ${battlePath}`);
    }
  } else {
    console.log('  ⚠️ No battles directory found');
  }

  console.log('\n══════════════════════════════════════════');
  console.log('  DEVSTRAL vs DEVSTRAL ABLITERATED');
  console.log('  Both sites opened in browser — judge them!');
  console.log('══════════════════════════════════════════\n');
});
